---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: catfacts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The project for catfacts
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catfacts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: catfacts
    name: in-cluster
  project: catfacts
  source:
    path: .
    repoURL: https://github.com/brasstax/catfacts-helm.git
    targetRevision: main
    valueFiles:
      - values.yaml
